# Generated by Django 5.1.4 on 2024-12-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spApp', '0002_coursetbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetbl',
            name='details',
            field=models.TextField(default='x'),
        ),
    ]
