# Generated by Django 5.1.4 on 2024-12-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spApp', '0003_coursetbl_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetbl',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
