# Generated by Django 5.1.4 on 2024-12-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spApp', '0004_coursetbl_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetbl',
            name='mediaFile',
            field=models.TextField(default='x'),
        ),
    ]
