# Generated by Django 5.1.4 on 2024-12-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spApp', '0005_coursetbl_mediafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetbl',
            name='image',
            field=models.TextField(default='x'),
        ),
    ]
