# Generated by Django 5.1.4 on 2024-12-24 06:57

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spApp', '0006_coursetbl_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetbl',
            name='details',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='coursetbl',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='uploads/'), upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='coursetbl',
            name='mediaFile',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
