# Generated by Django 5.1.4 on 2024-12-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spApp', '0007_alter_coursetbl_details_alter_coursetbl_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetbl',
            old_name='details',
            new_name='content',
        ),
        migrations.AddField(
            model_name='coursetbl',
            name='duration',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='coursetbl',
            name='instructor',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='coursetbl',
            name='level',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='coursetbl',
            name='overview',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='coursetbl',
            name='user',
            field=models.TextField(default=''),
        ),
    ]
