# Generated by Django 5.1.4 on 2024-12-26 06:51

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spApp', '0008_rename_details_coursetbl_content_coursetbl_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetbl',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='uploads/'), upload_to='courseImages/'),
        ),
        migrations.AlterField(
            model_name='coursetbl',
            name='mediaFile',
            field=models.FileField(upload_to='courseVideos/'),
        ),
    ]
