# Generated by Django 5.1.4 on 2024-12-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spApp', '0010_alter_coursetbl_description_coursecontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='content_file',
            field=models.FileField(upload_to='coursesContent/'),
        ),
    ]
