# Generated by Django 5.1.4 on 2024-12-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spApp', '0011_alter_coursecontent_content_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_date',
        ),
    ]
